apiVersion: v1
entries:
  chis:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-09-17T09:21:57.577641271Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 3a3550a30c26fd393fee67aa0b3de88ad6676ca4b2a956a37c6f8815960e7e7e
    home: chis.zaakonline.nl
    icon: chis.zaakonline.nl
    name: chis
    urls:
    - chis-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-17T09:21:57.567810471Z"
